query categoryByTitle($categoryInput: CategoryInput!) {
  category(input: $categoryInput) {
    name
    products{
      id,
      name,
      gallery,
      inStock,
      description,
      prices {
        currency {
          label,
          symbol
        }
        amount
      }
    }
  }
}
